POST http://127.0.0.1:8080/v1/get
Content-Type: application/json

{
  "Token": "WORLD",
  "UserID": "HELLO",
  "UserPW": ":-)"
}

###
PUT http://127.0.0.1:8080/api/v1/client
Content-Type: application/json

{
  "clientId": "rabums",
  "clientPw": "SOMETHING ELSE",
  "link": "https://iwanhae.ga",
  "description": "2것은 실험용입니다.",
  "valid": true,
  "renewToken": true
}
###
PUT http://127.0.0.1:8080/api/v1/client
Content-Type: application/json

{
  "clientId": "rabums",
  "originalPw": "SOMETHING ELSE",
  "link": "https://iwanhae.ga/avas"
}
###
POST http://127.0.0.1:8080/api/v1/user
Content-Type: application/json

{
  "token": "dcd08e8f5ef7dbbc06364709a595ad7269e78f8524df674477624c671708093c",
  "userId": "train96",
  "userPw":"960ba2cd3d1b0dff855351028812d17d2787adaa3b2d0ee527b2b633c7d15afc"
}


###
PUT http://127.0.0.1:8080/v1/user/request/token
Content-Type: application/json

{
  "userName": "이완해",
  "userNumber": -1,
  "userEmail": "train96@uos.ac.kr",
  "userId": "train96",
  "userPw": "test2"
}
###
PUT http://127.0.0.1:8080/v1/user/request/register
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpZXJzX2F0IjoiMjAyMC0wOC0xN1QxNToxMzo0MSswOTowMCIsInVzZXJFbWFpbCI6InRyYWluOTZAdW9zLmFjLmtyIiwidXNlcklkIjoidHJhaW45NiIsInVzZXJOdW1iZXIiOjB9.97qmXFN9BP-mH_DalKA7m_aKSfMrb2TZNgGKlZP5x-g"
}