// Code generated by entc, DO NOT EDIT.

package clientserver

import (
	"time"
)

const (
	// Label holds the string label denoting the clientserver type in the database.
	Label = "client_server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientName holds the string denoting the client_name field in the database.
	FieldClientName = "client_name"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAvailable holds the string denoting the available field in the database.
	FieldAvailable = "available"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"

	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the clientserver in the database.
	Table = "client_servers"
	// EventsTable is the table the holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "event_clientserver"
	// OwnerTable is the table the holds the owner relation/edge. The primary key declared below.
	OwnerTable = "client_server_owner"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
)

// Columns holds all SQL columns for clientserver fields.
var Columns = []string{
	FieldID,
	FieldClientName,
	FieldToken,
	FieldLink,
	FieldDescription,
	FieldAvailable,
	FieldCreatedAt,
}

var (
	// OwnerPrimaryKey and OwnerColumn2 are the table columns denoting the
	// primary key for the owner relation (M2M).
	OwnerPrimaryKey = []string{"client_server_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
