// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/CSUOS/rabums/ent/clientserver"
	"github.com/CSUOS/rabums/ent/predicate"
)

// ClientServerDelete is the builder for deleting a ClientServer entity.
type ClientServerDelete struct {
	config
	hooks    []Hook
	mutation *ClientServerMutation
}

// Where adds a new predicate to the ClientServerDelete builder.
func (csd *ClientServerDelete) Where(ps ...predicate.ClientServer) *ClientServerDelete {
	csd.mutation.predicates = append(csd.mutation.predicates, ps...)
	return csd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (csd *ClientServerDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(csd.hooks) == 0 {
		affected, err = csd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClientServerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			csd.mutation = mutation
			affected, err = csd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(csd.hooks) - 1; i >= 0; i-- {
			mut = csd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, csd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (csd *ClientServerDelete) ExecX(ctx context.Context) int {
	n, err := csd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (csd *ClientServerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: clientserver.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clientserver.FieldID,
			},
		},
	}
	if ps := csd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, csd.driver, _spec)
}

// ClientServerDeleteOne is the builder for deleting a single ClientServer entity.
type ClientServerDeleteOne struct {
	csd *ClientServerDelete
}

// Exec executes the deletion query.
func (csdo *ClientServerDeleteOne) Exec(ctx context.Context) error {
	n, err := csdo.csd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clientserver.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (csdo *ClientServerDeleteOne) ExecX(ctx context.Context) {
	csdo.csd.ExecX(ctx)
}
