# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: csuos # optional
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_PW }}
        # Docker repository to tag the image with
        repository: csuos/rabums
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true # optional
        # Comma-delimited list of images to consider as cache sources
        cache_froms: csuos/rabums:latest # optional
        # Comma-delimited list of labels to add to the built image
        labels: builder=github_actions # optional
        # Adds labels with git repository information to the built image
        add_git_labels: true # optional