// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ClientServer is the predicate function for clientserver builders.
type ClientServer func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
